name: Run Basic Testes - Agendamento

on:
  schedule:
    - cron: '0 20 * * 1-5'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v3

      - name: Run testes
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}

      - name: upload relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatório
          path: cypress/reports/html

          